unbind r
bind r source-file ~/.tmux.conf
set -g mouse on
#set -g default-shell ~/.local/bin/ttyrell
bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D
set-option -g status-position top
set-option -g base-index 1
set-option -g renumber-windows on
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @llugin 'tmux-plugins/resurrect'
set -g @llugin 'tmux-plugins/continuum'
run '~/.config/tmux/plugins/tpm/tpm'
run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

run ~/.config/tmux/plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-battery/battery.tmux

